version: "3"

services:

  py-dot-proxy:
    build: ./
    image: py-dot
    container_name: py_dot_instance
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      MAX_PAYLOAD_LENGTH: "1024"
    networks:
      - py_dot_network

networks:
  py_dot_network:
    driver: bridge
